### ISSUE TITLE
rake specs fail

### ISSUE THREAD

**Issue by wtn** [kristianmandrup/mongoid-geo#10]
(in mongoid-geo)
/usr/local/rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/rake.rb:30: warning: already initialized constant RAKEVERSION
WARNING: Possible conflict with Rake extension: String#ext already exists
WARNING: Possible conflict with Rake extension: String#pathmap already exists
/usr/local/rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/rake.rb:402: warning: already initialized constant EMPTY_TASK_ARGS
/usr/local/rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/rake.rb:450: warning: already initialized constant EMPTY
/usr/local/rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/rake.rb:958: warning: already initialized constant RUBY_EXT
/usr/local/rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/rake.rb:962: warning: already initialized constant RUBY
/usr/local/rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/rake.rb:1031: warning: already initialized constant LN_SUPPORTED
/usr/local/rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/rake.rb:1240: warning: already initialized constant ARRAY_METHODS
/usr/local/rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/rake.rb:1243: warning: already initialized constant MUST_DEFINE
/usr/local/rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/rake.rb:1247: warning: already initialized constant MUST_NOT_DEFINE
/usr/local/rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/rake.rb:1251: warning: already initialized constant SPECIAL_RETURN
/usr/local/rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/rake.rb:1257: warning: already initialized constant DELEGATING_METHODS
/usr/local/rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/rake.rb:1561: warning: already initialized constant DEFAULT_IGNORE_PATTERNS
/usr/local/rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/rake.rb:1567: warning: already initialized constant DEFAULT_IGNORE_PROCS
/usr/local/rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/rake.rb:1604: warning: already initialized constant FileList
/usr/local/rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/rake.rb:1630: warning: already initialized constant EARLY
/usr/local/rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/rake.rb:1960: warning: already initialized constant DEFAULT_RAKEFILES
rake aborted!
stack level too deep
/usr/local/rvm/gems/ruby-1.9.2-p180/gems/rake-0.8.7/lib/rake.rb:2383

**Comment by kristianmandrup** [comment]
The specs run just fine for me.

<pre>
$ rspec spec/mongoid/geo/
.......................................
$ ruby -v
ruby 1.9.2p136 (2010-12-25 revision 30365) [x86_64-darwin10.6.0]
</pre>


But using rake, I get that same error...

<pre>
$ rake -v
(in /Users/kristianconsult/Development/Languages/Ruby/Apps/Gems/mongoid_geo)
/Users/kristianconsult/.rvm/rubies/ruby-1.9.2-p136/lib/ruby/1.9.1/rake.rb:30: warning: already initialized constant RAKEVERSION
WARNING: Possible conflict with Rake extension: String#ext already exists
WARNING: Possible conflict with Rake extension: String#pathmap already exists
/Users/kristianconsult/.rvm/rubies/ruby-1.9.2-p136/lib/ruby/1.9.1/rake.rb:402: warning: already initialized constant EMPTY_TASK_ARGS
</pre>

**Comment by wtn** [comment]
Thanks, I'll use the rspec command for now.

I noticed that two specs are failing:

  1) Mongoid::Geo::Near geoNear option :maxDistance should limit on maximum distance
     Failure/Error: Address.geoNear(address, :location, :maxDistance => 0.2).size.should == 1
       expected: 1
            got: 2 (using ==)
     # ./spec/mongoid/geo/geo_near_spec.rb:36:in `block (4 levels) in <top (required)>'

  2) Mongoid::Geo::Near geoNear option :query should filter using extra query option
     Failure/Error: Address.geoNear(address, :location, :query => {:city => 'Munich'}).size.should == 1
       expected: 1
            got: 2 (using ==)
     # ./spec/mongoid/geo/geo_near_spec.rb:50:in `block (4 levels) in <top (required)>'

**Comment by kristianmandrup** [comment]
Have been fixed
