### ISSUE TITLE
to_model doesn't work with latest Mongoid

### ISSUE THREAD

**Issue by erikostling** [kristianmandrup/mongoid-geo#12]
The search query in to_model (geo_near.rb) returns a nil value.

Changing this:

  klass.where(:_id => _id).first.extend(Mongoid::Geo::Distance)

to:

  klass.criteria.id(_id).first.extend(Mongoid::Geo::Distance)

might solve it…?

**Comment by kristianmandrup** [comment]
oh? Please try it out and send me a pull request if it works. Thanks.

**Comment by erikostling** [comment]
Sent you a pull request now. It's my first time at this though so check it out carefully. Also it's 00:40 am so that should be taken into consideration to. ;)

**Comment by kristianmandrup** [comment]
Thanks. I will look at it in the morning ;)
