### ISSUE TITLE
store geo data and using Spherical Model

### ISSUE THREAD

**Issue by niedhui** [kristianmandrup/mongoid-geo#16]
mongoid-geo assume the location data is stored as [lat,lng], but if I want to use Spherical Model of monodb,it must stored as [lng,lat]. does mongoid-goe has any plan or suggestion for this?

**Comment by gerred** [comment]
+1

**Comment by kristianmandrup** [comment]
Check out the latest 0.4.2 version. Now has support for a sperical coordinate save mode that reverses lng/lat positioning in the Array. Can be used either within a block or globally. See the new spec for usage examples.

**Comment by kristianmandrup** [comment]
Please check the mongo_18_spherical branch and help me fix this issue. Almost there!

**Comment by kristianmandrup** [comment]
This should work now
