### ISSUE TITLE
if trying to save array, first (lat) is always 0

### ISSUE THREAD

**Issue by victorbstan** [kristianmandrup/mongoid-geo#18]
if I have a form field with values populated from the database of existing latlng values...

So that in model: 

Field :latlng, :type => Float, :geo => true

then

in view i have a form field: 

map[latlng] with values: "[some lat number float, some lng number float]" 

on save, the database persists:

[0, some lng number float]

**Comment by kristianmandrup** [comment]
I am in China all of April and unable to debug and fix this myself. Please see if you can debug this error, provide a fix and make a pull request. Thanks! Kristian

**Comment by danielfarrell** [comment]
Not sure if I'm following completely, but try making your :type be Array.

**Comment by kristianmandrup** [comment]
Yeah, it definitely should be an Array type!
