### ISSUE TITLE
nil distance

### ISSUE THREAD

**Issue by wtn** [kristianmandrup/mongoid-geo#20]
Hi,
I get `nil` as the return value for the following method call:  
  Place.geoNear(another_place.location, :location).first.to_model.distance

Every item in the result set returns `nil` for distance.

I'm using Mongoid 2.0.1 and Mongo 1.8.0.  
I set `Mongoid::Geo.mongo_db_version = 1.8` in an initializer.

**Comment by kristianmandrup** [comment]
Please try debugging this issue and pay special attention to the #create_query and #query_result methods in the geo_near.rb file. Would be awesome if you could fix this :) 
I have previously only tested with Mongo DB 1.6.3. The 1.7 and 1.8 related code has been submitted by others. 
I am now installing 1.8.1 so I can check this out too and work on it.

**Comment by revans** [comment]
I'm using mongodb 1.8.1 and i don't have this issue when using geoNear.

**Comment by kristianmandrup** [comment]
@wtn if you just want distance calculations, you might wanna use my _geo-distance_ gem instead ;)
But using Mongo 1.8 native distance calculations should be way faster I think. Anyone for a geoNear metrics test of ruby Haversine vs Mongo 1.8 distance calc for say 1.000 points?

**Comment by revans** [comment]
I haven't benchmarked it but, there is a noticeable different in the browser when using Mongo's distance calc.

**Comment by kristianmandrup** [comment]
Just added a benchmark spec to the mix:

@center  = Address.create(:location => {:lat => 31.5, :lng => -121.5}, :city => 'center')  
5000.times do
   Address.create(:location => {:lat => 31 + delta, :lng => -121 + delta})
end      

puts Benchmark.measure { Address.geoNear @center.location, :location, :unit => :km }

Mongoid spherical geoNear distance calculations
  Spherical mode distance
    Mongo DB < 1.7
  0.080000   0.000000   0.080000 (  0.083754)
      calculates distance using ruby Haversine code
    Mongo DB 1.8
  0.000000   0.000000   0.000000 (  0.007230)
      calculate distance using Mongo 1.8 native distance calculation

Looks like a 10x speed improvement!

**Comment by revans** [comment]
Nice.

**Comment by kristianmandrup** [comment]
Done
