### ISSUE TITLE
Invalid gemspec in [mongoid_geo-0.4.2.gemspec]: invalid date format in specification: "2011-05-03 00:00:00.000000000Z"

### ISSUE THREAD

**Issue by ryanong** [kristianmandrup/mongoid-geo#25]
Not sure why this is the case. I think it is the way it is processed by rubygems.org you might want to look into using jewler to package your gem makes life a lot easier.

**Comment by kristianmandrup** [comment]
Hmm... this is actually one of my first gems for which I haven't used jeweler ;P
@codewranglers submitted the patch to add the date to the gemspec.

https://github.com/kristianmandrup/mongoid-geo/pull/19

Maybe the date conflicts on different Rubygems versions?

Please see which date format works for you and let me know your rubygems version. I might consider switching to jeweler too ;)

**Comment by revans** [comment]
The date that I (i run @codewranglers) added fixes this issue.

**Comment by kristianmandrup** [comment]
Done ;)
