### ISSUE TITLE
Maintain Distance Calculations in Mongoid::Criteria

### ISSUE THREAD

**Issue by revans** [kristianmandrup/mongoid-geo#26]
When doing to_criteria on a result set, what's the best way to keep the distance intact and keep the sort order based on distance?

**Comment by revans** [comment]
Context: I'm doing the following query:

Course.geoNear([lat, long], :lat_long, {:mode => :sphere, :maxDistance => radius, :distanceMultiplier => 3963.19})

Which gives me an array of Hashie mash. What I want is to have a Mongoid::Criteria so I can do pagination on it with kaminari. I don't want to lose the distance calculations already made. 

I didn't see anything in mongoid-geo source to indicate that this is possible, but I could have easily missed it.

**Comment by kristianmandrup** [comment]
I haven't yet attempted to create a Mongoid::Criteria from the Hashie. 
Feel free to hack away and produce a patch to add such functionality :)
The distanceMultiplier you are using looks interesting! Which unit is that for?
I have been trying to add a :unit option instead (see unit.rb) to facilitate this.

**Comment by revans** [comment]
The distanceMultiplier is for miles. I did see the :unit option, but had not tried it. 

The to_criteria method in the Mongoid::Geo::Models does return a Mongoid::Criteria class, but it doesn't perserve the distance var, obviously since the to_criteria method is just a where(...) method for the collection of ids. 

I'll look into it more and see if I can come up with something.

**Comment by kristianmandrup** [comment]
Try something like this perhaps? 

```
  def to_criteria
    ids = map(&:_id)
    Mongoid::Criteria.new(first.klass).where(:_id.in => ids).desc(:distance)
  end
end
```

**Comment by kristianmandrup** [comment]
I think for Criteria to work, distance must be added as a field, either to the class or each instance resulting from the query. Try experimenting a bit...  

   module Distance  
      def self.extended(base)
        base.field :distance, :type => Float
      end

```
  def set_distance dist
    @distance = dist
  end
end

module Model
  def to_model
    m = klass.where(:_id => _id).first.extend(Mongoid::Geo::Distance)
    m.set_distance distance
    m
  end
end

module Models
  def to_models
    distance_hash = Hash[ self.map {|item| [item._id, item.distance] } ]

    ret = to_criteria.to_a.map do |m|
      m.class.extend(Mongoid::Geo::Distance) 
```

...

```
  def to_criteria
    ids = map(&:_id)  
    # first.klass.where(:_id.in => ids)
    Mongoid::Criteria.new(first.klass).where(:_id.in => ids).desc(:distance)
  end      
```

**Comment by kristianmandrup** [comment]
I Think a good solution is simply to add a distance field as part of the fields setup (executed by the :geo => true). 
Then add a desc(:distance) to the to_criteria method.

**Comment by revans** [comment]
I got something working in the meantime, but I'll give these a try out and see where i get.

**Comment by kristianmandrup** [comment]
Please if you find a good sultion for this, patch the gem and make a pull request. Would be the last missing piece I think :)

**Comment by kristianmandrup** [comment]
Ah, :distance (Float) should always be added as a field for the class and also a :from (String). Then you simply make the criteria where(:_id => ids, :from => city.name).desc(:distance), then you get all with descending distance from the given (named) point. Here city is an instance of the same class.

**Comment by kristianmandrup** [comment]
Latest commit and release should now fully support converting result into a Mongoid::Criteria if needed ;)
Oh, I think that should be the default and then #to_a would convert the criteria into a model as is the standard.

**Comment by revans** [comment]
You rock man! I hadn't even had a chance yet to dig more into it. :)

**Comment by kristianmandrup** [comment]
Thanks. Just updated it a little bit more, so u now always have access to the locationPoint the distance was calculated from.
Any other ideas/feature requests for the gem? Otherwise I might as well make it 1.0.

**Comment by revans** [comment]
No ideas/requests at this moment. Looks good man! Great job!
