### ISSUE TITLE
undefined method 'distance=' for Model

### ISSUE THREAD

**Issue by graybill** [kristianmandrup/mongoid-geo#27]
I apologize if this is user error  or an obvious oversight on my part. I am trying various geoNear queries and am getting "undefined method 'distance=' for Model" 

gem 'rails', '3.0.5'
gem 'mongoid', "~> 2.0.1"
gem 'mongoid_geo', "0.5.2"

class Place
  include Mongoid::Document
  extend Mongoid::Geo::Near
  field :loc, type: Array, :geo => true
  geo_index :loc
end

@places = Place.geoNear([lat, long], :loc)

And the resulting error:
NoMethodError (undefined method `distance=' for #<Place:0x00000103a29b90>):
  app/controllers/places_controller.rb:19:in`index'

**Comment by kristianmandrup** [comment]
This works for me:

<pre>
class Place
 include Mongoid::Document
 extend Mongoid::Geo::Near
 field :loc, type: Array, :geo => true
 geo_index :loc
end

Place.collection.create_index([['loc', Mongo::GEO2D]], :min => -180, :max => 180)

describe Mongoid::Geo::Near do

  describe 'place' do
    before(:each) do
      Place.create(:loc => [45, 11])
      Place.create(:loc => [46, 12])
    end

    it 'should return places near' do
      @places = Place.geoNear([44, 11.5], :loc)
      pp @places.to_a
    end
  end
end
</pre>


Run:

<pre><code>
Mongoid::Geo::Near
  place
#Place _id: 4dc84db860de7d0539000003, _type: nil, _id: BSON::ObjectId('4dc84db860de7d0539000003'), loc: [45.0, 11.0], distance: 1.1180369209107197, fromHash: "-1496252397791315677", fromPoint: [44, 11.5]>,
#Place _id: 4dc84db860de7d0539000004, _type: nil, _id: BSON::ObjectId('4dc84db860de7d0539000004'), loc: [46.0, 12.0], distance: 2.0615530151967376, fromHash: "-1496252397791315677", fromPoint: [44, 11.5]>
    should return places near
</code></pre>

**Comment by kristianmandrup** [comment]
I've added this as an additional spec, pushing it now ;)

**Comment by graybill** [comment]
Thank you for the response and test code. I'll keep playing with it, thanks.
