### ISSUE TITLE
Invalid date format in gemspec

### ISSUE THREAD

**Issue by Pesa** [kristianmandrup/mongoid-geo#29]
Invalid gemspec in [/Library/Ruby/Gems/1.8/specifications/mongoid_geo-0.5.3.gemspec]: invalid date format in specification: "2011-05-09 00:00:00.000000000Z"

I'm using ruby 1.8.7 and rubygems 1.7.2 on mac OS X.

**Comment by kristianmandrup** [comment]
Just pushed a fix now and updated the API and README. Check out the latest gem and release 0.5.4.

**Comment by Pesa** [comment]
Thanks a lot!

**Comment by Pesa** [comment]
I've updated to 0.5.4, but this issue is still not fixed. The error is the same:

Invalid gemspec in [/Library/Ruby/Gems/1.8/specifications/mongoid_geo-0.5.4.gemspec]: invalid date format in specification: "2011-05-09 00:00:00.000000000Z"

**Comment by kristianmandrup** [comment]
Hmm, it installs ok for me. Try to clone the repo then remove the date part in the gemspec and run.

$ rake install

Someone complained that it didn't work without the date part in the gemspec. Now I tried two different ways to define it.

**Comment by Pesa** [comment]
It does install correctly using rubygems, but when i run other commands (e.g. bundle, gem outdated, etc..) it throws that error and the gem is treated as not installed. I cannot even uninstall it with rubygems, I have to do it manually.

**Comment by kristianmandrup** [comment]
Let me know if it works for you by removing the date part in the gemspec. It should default to Time.now if not there according to the RubyGems manual.

**Comment by Pesa** [comment]
Unfortunately rake fails quite early with:
rake aborted!
no such file to load -- rake/rdoctask

**Comment by kristianmandrup** [comment]
Hmm, then uncomment the rdoc part in the gemspec (only generates some documentation that u are unlikely to use). 
I assume its 'coz that you don't have rdoc installed?

**Comment by Pesa** [comment]
I do have rdoc installed... anyway, even after commenting out both RSpec and RDoc tasks from the Rakefile, it fails with:
Don't know how to build task 'install'

Btw, rake -T does not display any available tasks. I have rake 0.8.7 installed, do I need something else?

**Comment by kristianmandrup** [comment]
Ah yeah, this gem is not based on jeweler!

This should work:
$ gem build mongoid-geo.gemspec
$ gem install pkg/mongoid_geo-0.5.4.gem

Or something similar.

Also try this: make sure you have jeweler installed, then:
$ jeweler my_gem
$ cd my_gem
$ rake -T
$ rake install

This should install a jeweler based "empty" gem. 
I will soon port mongoid-geo to be based on jeweler as this makes it all easier ;)

**Comment by Pesa** [comment]
ok, after removing the date in the gemspec, I ran gem build && gem install.
And it worked finally! Thank you!

**Comment by kristianmandrup** [comment]
Finally :) Just removed it from the gemspec and released a patch version 0.5.4.1

**Comment by Pesa** [comment]
I don't see the commit on github however, did you forget to push it?
Btw you should tag releases on git, I believe it's a common and useful practice...

**Comment by Pesa** [comment]
Uhm... the latest gem on rubygems.org is still broken as before :-/

**Comment by kristianmandrup** [comment]
Strange!? I removed the date from the gemspec, as you can see on the latest (tagged) github commit

**Comment by Pesa** [comment]
There must be an issue with the gem packaging... what version of rubygems are you using?
