### ISSUE TITLE
Gemfile issues

### ISSUE THREAD

**Issue by davemitchell** [kristianmandrup/mongoid-geo#37]
A few small (breaking) issues in the current gemfile:
- Broken for jruby; the bundler keyword should be :platforms (plural) not :platform on the bson_ext line
- I don't think you need to include the bson reference in the gemfile, I believe it's included as a dependency in mongoid
- Bundle install breaks because geo_vectors gemfile specifies shugar-high >= 0.4.1, while the latest version in rubygems.org is 0.4.0
- Should geo_calc and geo_vectors gems be listed in the root, or are they really only used under test/development?

I started to test in my fork, but ran into the sugar-high dependency issue... Kristian, I haven't looked closely to see how calc and vectors are being used and am heading out the door for meetings now.  Here's the minor gemfile edit I was trying to test:

```
source :rubygems

gem 'mongoid',        '>=2'
gem "bson_ext",       '>=1.3',  :platforms => :mri
gem 'activesupport',  '>=3'
gem 'geo_calc', '~> 0.6.1'
gem 'geo_vectors', '~> 0.5.1'  

group :test, :development do
  gem 'rspec',    '>=2.4'
  gem 'bundler',  '>=1'
  gem 'jeweler',  '>=1.5'
  gem 'rdoc',     '>=3.6'
end

group :test do
  gem 'rails',        '>=3.0'
  gem 'rspec-rails',  '>=2.6'
  gem 'capybara',     '>=0.4'
end
```

**Comment by kristianmandrup** [comment]
Thanks! I've just fixed it. Release an updated sugar-high v. 0.4.4 and fixed the Gemfile :platforms option.
