### ISSUE TITLE
object.location.lat

### ISSUE THREAD

**Issue by TeuF** [kristianmandrup/mongoid-geo#4]
Hi,

I like this plugin now ! ;) And I just wonder if it would be possible to get the lat and lng in a way like this:

<pre>
object.location.lat
object.location.lng
</pre>

Does it make sense ?
Thanks,

**Comment by kristianmandrup** [comment]
Yeah! Makes sense ;) I'm sure you can make your own little patch to wrap this, no?
:) Then give me a pull request.

**Comment by kristianmandrup** [comment]
OK, I made the fix and also auto require the fields.rb as it should not conflict anymore.
Hope u like it (v. 0.1.6)

**Comment by TeuF** [comment]
First quick and dirty solution that solved my problem.
https://github.com/TeuF/mongoid-geo/commit/677f9b75abc13e5308412f650691538de6a31b6b

But yes really dirty :(

**Comment by kristianmandrup** [comment]
I think my latest commit which enables this for both #location and #position where either can contain the #lat, #lng attributes is a little better. I extended the #to_point method instead ;) Cheers!
