### ISSUE TITLE
Uninitialized constant Mongoid::Geo

### ISSUE THREAD

**Issue by baldrailers** [kristianmandrup/mongoid-geo#40]
I'm currently using your gem in my project. After doing a bundle update, i got this error. My `Gemfile` is configured to pull the `master` branch of this code. I've got the issue with `19801bad24fa1649f431` commit:

Here's the full stack trace: https://gist.github.com/1016367

Thanks!

**Comment by kristianmandrup** [comment]
Yeah, sorry, please don't pull the master just now :P 
We are working on releasing a 1.0 version sometime next week hopefully. 
Please use a released gem version for now. You are most welcome to help with development of mongoid_geo...
For starters we need to clean up the specs! I've started this on a 1_0_beta branch.
Cheers!

**Comment by baldrailers** [comment]
Cool. I already forked this. 

Thanks!
