### ISSUE TITLE
Bug in geo_near

### ISSUE THREAD

**Issue by lukas2** [kristianmandrup/mongoid-geo#43]
Quick bug-report:

When using the `geo_near` method, it fails, if the `klass` has a namespace-name, e.g. `Foo::Bar::Model`. The result is that the collection-name sent to mongo will look like this: `foo/bar/model` instead of `foo_bar_model`.

I've monkey patched this in my project, but perhaps you can fix it in the gem as well.

**Comment by ryanong** [comment]
Check out mongoid_spacial I basically coded it from the ground up. a lot cleaner and a lot faster.

**Comment by kristianmandrup** [comment]
cool :) I haven't had time to look much into mongoid-geo since ryan took the main ideas and created his own working gem.
I'm just happy that there are finally some working mongoid geo related gems out there - then ppl can go from there and hopefully use these as a base for some powerful solutions. I would like to see it integrated with geocoder fx.
You are most welcome to send me a pull request with your fix. Cheers!

**Comment by lukas2** [comment]
Thank you, I wasn't aware of it.

**Comment by kristianmandrup** [comment]
@lukas2, please send me a pull request with your fix! thanks!

**Comment by lukas2** [comment]
Hi, I think my fix isn't really working well and meanwhile we've switched to the mongo driver. Sorry, no fix at this time..

**Comment by kristianmandrup** [comment]
OK, then just publish a gist or sth. with your changes and I can on work from there on my own ;)

**Comment by kristianmandrup** [comment]
@lukas2, did you get the gem to work with your monkeypatch? I would much like to see what you have done. I don't like to have "dead beat" code lying around too much on my github account ;)

**Comment by lukas2** [comment]
Sorry for the late reply. 
Anyway, I decided after a while to use the ruby driver instead of mongoid_geo. I couldn't get it to work.
Perhaps the error was elsewhere anyway.

**Comment by kristianmandrup** [comment]
mongoid_geo is dead for now! I haven't had time to polish the last tidbits to make it work. 
A much better option is mongoid_spatial by @ryanong, which has taken much of the mongoid_geo infrastructure, reworked it and added features such as pagination etc. It is well and alive and actively maintained to my knowledge ;) 
Good luck!

**Comment by lukas2** [comment]
Alrighty.
Thanks for the information on the alternative gem.

**Comment by kristianmandrup** [comment]
I have now updated the README to redirect developers to mongoid_spacial as the better option ;)
