### ISSUE TITLE
Support for GeoNear

### ISSUE THREAD

**Issue by guus2006** [kristianmandrup/mongoid-geo#5]
Hi,

Are there any plans to add support for Mongoid Geonear queries ? It has the added information about distance to the location. I need this information in my app.

regards

Jeroen

**Comment by kristianmandrup** [comment]
Hi Jeroen,

I think that would be a wonderful addition. I remember I looked at it but wasn't sure how to implement it at that time. Now I have constructed a pretty decent framework for adding additional criterias to Mongoid. I'm sure you could easily get the hang of it and roll such an implementation addition yourself. Then just send me a pull request and I will merge it right in! I'm sure it will take a couple of hours max, complete with the specs, but I'm busy myself on other matters now... Have fun!

Kris

**Comment by guus2006** [comment]
The issue with geonear is that it is not part of the find method put runs as a seperate command (runcommand) in mongo.

ex: workplace_development['$cmd'].find({"geoNear"=>"locations", "near"=>[4.8922222, 52.3730556]})

I have not found an easy way yet to use runcommand in Mongoid

**Comment by kristianmandrup** [comment]
I've just mailed Kyle Banker about it (author of Mongo ruby driver?).
I also found this note on it:

http://groups.google.com/group/mongodb-user/browse_thread/thread/da07558c643ab39d

Have you found ANY? way of running such a command in Ruby? What ruby Class is the _workplace_development_ in your example?

**Comment by guus2006** [comment]
workplace_development is my mongo DB. I copy pasted the Logger output from my rails console. I have a working example of geonear but the output does not go through mongoid, so you loose all the nice features and benefits. ( it is a tough hack, that is why I am working on a nicer solution). Locations the model, lon_lat is the geoindex field. After the result I run it through Haversine method because I run Mongo 1.6 and Sphere is not supported yet.

git://gist.github.com/849669.git

**Comment by kristianmandrup** [comment]
Nice :) I just found this

http://api.mongodb.org/ruby/current/Mongo/DB.html#command-instance_method

But I can see you are already using it!

Do you have a gist of a complete self-contained sandbox example of this that works out of the box? Then I will try to "package it" and add it to mongoid_geo. Thanks :)

**Comment by kristianmandrup** [comment]
This is as close as I can get now... still not sure about the _lon_lat_ variable in your example however...

<pre>
require 'rubygems'
require 'mongo'
require 'mongoid'
require 'mongoid_geo'

class Location
  include Mongoid::Document
  
  field :lon_lat, :type => Array, :geo => true  
end

l1 = Location.create :lon_lat => [45, 11]
l2 = Location.create :lon_lat => [45, 11]

query = BSON::OrderedHash.new.tap do |query|
   query["geoNear"]="locations"
   query["near"] = lon_lat
end

lon,lat = lon_lat

query = Location.collection.db.command(query)['results'].sort_by do |r|
  r['distance'] = Haversine.distance(lat, lon, r['obj']['lon_lat'][1], r['obj']['lon_lat'][0])
end
</pre>

**Comment by guus2006** [comment]
the lon_lat variable is the result of a geosearch with google maps. Someone wants to lookup the locations closest to a certain city. I look up the lon_lat with Google and then do the Geonear.
