### ISSUE TITLE
how to install mongoid_geo?

### ISSUE THREAD

**Issue by bopbi** [kristianmandrup/mongoid-geo#7]
i have include mongoid_geo in my gemfile
and this is my model

class Location
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, :type => String
  field :description, :type => String
  field :latlng, :type => Array, :geo => true

  geo_index :latlng

end

but when i create a location it shows error like this:

Field was defined as a(n) Array, but received a String with the value "-6.905033, 107.611539"

{"utf8"=>"âœ“",
 "authenticity_token"=>"SKXnsMo613fky4DMn2F9R0TiOul/21hSg+sk7GC7b4Q=",
 "location"=>{"name"=>"Saint Coffee",
 "description"=>"tempat ngopi",
 "address"=>"",
 "latlng"=>"-6.905033,
 107.611539",
 "accuracy"=>"0",
 "total_rating"=>"0",
 "total_comment"=>"0",
 "total_menu_rating"=>"0",
 "total_menu_comment"=>"0"},
 "commit"=>"Create Location"}

am i missing something when i install mongoid_geo gem

**Comment by kristianmandrup** [comment]
Good point! I temporarily removed fields.rb from the require, since someone had an issue with it. I thought I had added it back in since 0.2.x but seems I never did.
0.3.1 Should fix this.

require 'mongoid/geo/fields'

**Comment by bopbi** [comment]
ok. i'm waiting for the 0.3.1

**Comment by kristianmandrup** [comment]
Just released 0.3.1 ;)

**Comment by bopbi** [comment]
ok thanks
